databases:
  - name: wellpathdb
    plan: free
    databaseName: wellpath_db
    user: wellpath_user

services:
  - type: web
    plan: free
    name: wellpath
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'cd WellPath && python -m gunicorn WellPath.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: wellpathdb
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "false"
      - key: ALLOWED_HOSTS
        value: your-render-domain.onrender.com
      - key: WEB_CONCURRENCY
        value: 4