# Generated by Django 5.2.3 on 2025-08-23 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_alter_goal_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
