# Generated by Django 5.2.3 on 2025-08-23 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_alter_category_options_category_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='goal',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='goals.category'),
        ),
        migrations.AddField(
            model_name='category',
            name='units',
            field=models.ManyToManyField(blank=True, related_name='categories', to='goals.unit'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='goals.unit'),
        ),
    ]
