# Generated by Django 5.2.3 on 2025-08-26 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0006_alter_unit_options_unit_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DailyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.FloatField()),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_progress', to='goals.goal')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('goal', 'date')},
            },
        ),
    ]
