# Generated by Django 5.2.3 on 2025-08-26 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0008_remove_goal_status_goal_completed_alter_goal_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
