# Generated by Django 5.2.3 on 2025-08-26 02:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0009_goal_finished_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='current_value',
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='goals.goal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'goal', 'date'), name='unique_daily_progress')],
            },
        ),
    ]
