# Generated by Django 5.2.3 on 2025-08-27 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0010_remove_goal_current_value_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='current_value',
            field=models.FloatField(default=0),
        ),
    ]
