# Generated by Django 5.2.3 on 2025-08-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0011_goal_current_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='progress_photos/'),
        ),
    ]
