# Generated by Django 5.2.3 on 2025-08-29 12:53

import django.db.models.deletion
import goals.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0012_progress_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='image',
        ),
        migrations.CreateModel(
            name='ProgressPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='progress_photos/', validators=[goals.models.ProgressPhoto.validate_image])),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='goals.progress')),
            ],
        ),
    ]
