# Generated by Django 5.2.3 on 2025-09-01 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0013_remove_progress_image_progressphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='overdue',
            field=models.BooleanField(default=False),
        ),
    ]
