# Generated by Django 5.2.3 on 2025-09-01 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0014_goal_overdue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='overdue',
        ),
    ]
