# Generated by Django 4.2.23 on 2025-09-05 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0016_comment_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['order'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=70, unique=True),
        ),
    ]
