# Generated by Django 4.2.23 on 2025-09-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0017_alter_unit_options_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
