# Generated by Django 5.2.6 on 2025-09-30 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0018_alter_category_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='current_value',
        ),
    ]
