"""
Django settings for WellPath project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import dj_database_url 

# Load enviroment variables for .env files
load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

import os
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'dev-only-insecure-key-change-in-prod')
DEBUG = bool(os.environ.get("DEBUG", default=0))
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'goals',
    'social',
    'taxonomy',
    'django_extensions',
    'rest_framework',
    'api', 
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'WellPath.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'goals.views.categories_context',
                'WellPath.context_processors.feature_flags',
            ],
        },
    },
]

WSGI_APPLICATION = 'WellPath.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Source - https://stackoverflow.com/a/50323012
# Posted by R.yan, modified by community. See post 'Timeline' for change history
# Retrieved 2026-05-04, License - CC BY-SA 4.0

# Database - Use dj_database_url for Render and production
# Falls back to local Postgres for development
if os.environ.get('DATABASE_URL'):
    # Render provides DATABASE_URL
    DATABASES = {
        'default': dj_database_url.config(default=os.environ.get('DATABASE_URL'), conn_max_age=600, conn_health_checks=True)
    }
else:
    # Local development with individual env vars
    DATABASES = {
        'default': {
            'ENGINE': os.environ.get('DATABASE_ENGINE', 'django.db.backends.postgresql_psycopg2'),
            'NAME': os.environ.get('POSTGRES_DB', 'wellpath_db'),
            'USER': os.environ.get('POSTGRES_USER', 'wellpath_user'),
            'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'wellpath_password'),
            'HOST': os.environ.get('POSTGRES_HOST', 'localhost'),
            'PORT': os.environ.get('POSTGRES_PORT', '5432'),
        }
    }



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True



STATIC_URL = 'static/'

if not DEBUG:
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = "goals.User"

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Django extensions
GRAPH_MODELS = {
  'app_labels': ["goals", "social", "taxonomy"],
  'group_models': True,
}

# Logging Configuration
LOG_LEVEL = os.environ.get('LOG_LEVEL', 'INFO')

# Determine if we should use file logging (not in CI)
USE_FILE_LOGGING = not os.environ.get('CI', False)

# Build handlers dict
_handlers = {
    'console': {
        'level': LOG_LEVEL,
        'class': 'logging.StreamHandler',
        'formatter': 'simple',
    },
}

# Only add file handler if not in CI and logs directory exists
if USE_FILE_LOGGING:
    logs_dir = BASE_DIR / 'logs'
    logs_dir.mkdir(exist_ok=True)
    _handlers['file'] = {
        'level': LOG_LEVEL,
        'class': 'logging.FileHandler',
        'filename': logs_dir / 'django.log',
        'formatter': 'verbose',
    }

# Determine which handlers to use for loggers
_log_handlers = ['console', 'file'] if USE_FILE_LOGGING else ['console']

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': _handlers,
    'loggers': {
        'django': {
            'handlers': _log_handlers,
            'level': LOG_LEVEL,
            'propagate': False,
        },
        'goals': {
            'handlers': _log_handlers,
            'level': LOG_LEVEL,
            'propagate': False,
        },
        'social': {
            'handlers': _log_handlers,
            'level': LOG_LEVEL,
            'propagate': False,
        },
        'taxonomy': {
            'handlers': _log_handlers,
            'level': LOG_LEVEL,
            'propagate': False,
        },
        'api': {
            'handlers': _log_handlers,
            'level': LOG_LEVEL,
            'propagate': False,
        },
    },
}

# -----------------------------------------------------------------------------
# Feature Flags
# -----------------------------------------------------------------------------
# Expose feature flags in a single place; values can be overridden via env vars.
def _env_bool(name: str, default: bool) -> bool:
    val = os.getenv(name)
    if val is None:
        return default
    return val.strip().lower() in {"1", "true", "yes", "on"}

FEATURE_FLAGS = {
    # Enable GPT-5 for all clients (toggleable via env var)
    "ENABLE_GPT5_FOR_ALL_CLIENTS": _env_bool("ENABLE_GPT5_FOR_ALL_CLIENTS", True),
}