# Generated by Django 5.2.6 on 2025-10-01 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Units',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('cat', models.CharField(max_length=64, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=70, unique=True)),
                ('units', models.ManyToManyField(blank=True, related_name='categories', to='taxonomy.unit')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order'],
            },
        ),
    ]
