name: Django Tests

on:
  push:
    branches:
      - "**"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r WellPath/requirements.txt

      - name: Run migrations
        run: |
          python manage.py migrate --noinput
        working-directory: WellPath

      - name: Run tests
        run: |
          python manage.py test
        working-directory: WellPath

    env:
      DJANGO_SECRET_KEY: testsecret
      DJANGO_SETTINGS_MODULE: WellPath.settings
